# Project Information
site_name: STOJ新老题解库
site_description: STOJ新老题解库，提供STOJ的题解，欢迎各位前来学习和交流。
site_author: TheMagicFlute
site_url: https://TheMagicFlute.github.io/STOJ-solutions-cpp/
strict: true

# Copyright
copyright: 'All codes and articals are provided under <a href="https://github.com/TheMagicFlute/STOJ-Solutions-cpp/blob/main/LICENSE">GNU GPLv3 License</a>. <br /> Copyright &copy; 2023-2024 LCL-Dev-Team <br/> Copyright &copy; 2025 <a href="https://github.com/TheMagicFlute" target="_blank">TheMagicFlute</a>. All Rights Reserved.'

# Repository Information
repo_name: 'TheMagicFlute/STOJ-Solutions-cpp'
repo_url: 'https://github.com/TheMagicFlute/STOJ-Solutions-cpp'
edit_uri: 'https://github.com/TheMagicFlute/STOJ-Solutions-cpp/edit/main/docs/{path}'

theme:
  name: 'material'
  static_templates:
    - 404.html
  language: 'zh'
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: true
  search_index_only: true
  favicon: 'favicon.ico'
  icon: 'material/school'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

nav:
  - 简介:
    - Home: index.md
  - 题解:
    - 老OJ:
      - '老OJ #1 A+B问题': old/solution1.md
  

  # - 题解: solutions.md
  # - 关于: about.md
